name: Deploy IA to EC2

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH key
        run: |
          echo "$EC2_SSH_KEY" > key.pem
          chmod 400 key.pem
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Connect and run Docker on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@184.73.65.186 << 'EOF'
            docker pull kamartinez/chatbot
            docker stop chatbot || true
            docker rm chatbot || true
            docker run -d -p 80:80 --restart unless-stopped --name chatbot kamartinez/chatbot
          EOF
